CREATE TABLE tb_account (
    id_account INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number VARCHAR(50) NOT NULL,
    CONSTRAINT uk_tb_account_document_number UNIQUE (document_number)
);
