CREATE TABLE tb_transaction (
    id_transaction INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_account INTEGER NOT NULL,
    id_operation_type INTEGER NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    event_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_transaction_account FOREIGN KEY (id_account)
        REFERENCES tb_account (id_account),
    CONSTRAINT fk_transaction_operation_type FOREIGN KEY (id_operation_type)
        REFERENCES tb_operation_type (id_operation_type)
);

CREATE INDEX idx_tb_transaction_id_account ON tb_transaction (id_account);
CREATE INDEX idx_tb_transaction_id_operation_type ON tb_transaction (id_operation_type);
